# Generated by Django 4.2.18 on 2025-01-24 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "label",
                    models.CharField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "model_city",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField()),
            ],
            options={
                "db_table": "model_company",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Establishment",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("label", models.CharField()),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establishment",
                        to="api.city",
                    ),
                ),
            ],
            options={
                "db_table": "model_establishment",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="ProjectManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField()),
            ],
            options={
                "db_table": "model_project_management",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField()),
            ],
            options={
                "db_table": "model_representative",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titreoperation", models.TextField()),
                ("montant_des_ap_votes_en_meu", models.FloatField(null=True)),
                ("enveloppe_prev_en_meu", models.FloatField(null=True)),
                ("notification_du_marche", models.DateField(null=True)),
                ("cao_attribution", models.DateField(null=True)),
                (
                    "annee_d_individualisation",
                    models.CharField(max_length=4, null=True),
                ),
                ("annee_de_livraison", models.CharField(max_length=4, null=True)),
                ("nombre_de_lots", models.IntegerField(null=True)),
                (
                    "mode_de_devolution",
                    models.CharField(
                        choices=[
                            ("Lots séparés", "Separate"),
                            ("Ent générale", "General"),
                            ("NC", "Nc"),
                        ],
                        default="NC",
                    ),
                ),
                ("ppi", models.CharField()),
                (
                    "etat_d_avancement",
                    models.CharField(
                        choices=[
                            ("Etudes et diagnostics", "Studies Diagnostics"),
                            ("Sélection mandataire", "Representative Selection"),
                            ("Sélection entreprise", "Company Selection"),
                            ("Etude de maîtrise d'œuvre", "Project Management Study"),
                            ("En Chantier", "Under Construction"),
                            ("Opération livrée", "Operation Delivred"),
                            ("Suspendue", "Suspended"),
                            ("Abandonné", "Cancceled"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="api.company",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="api.establishment",
                    ),
                ),
                (
                    "project_management",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="api.projectmanagement",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="api.representative",
                    ),
                ),
            ],
            options={
                "db_table": "model_project",
                "ordering": [
                    "annee_de_livraison",
                    "cao_attribution",
                    "notification_du_marche",
                ],
            },
        ),
    ]
