# Generated by Django 4.2.18 on 2025-01-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
            ],
            options={
                'db_table': 'model_city',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
            ],
            options={
                'db_table': 'model_company',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('code', models.CharField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField()),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to='api.city')),
            ],
            options={
                'db_table': 'model_establishment',
            },
        ),
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
            ],
            options={
                'db_table': 'model_project_management',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
            ],
            options={
                'db_table': 'model_representative',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreoperation', models.TextField()),
                ('montant_des_ap_votes_en_meu', models.FloatField(null=True)),
                ('enveloppe_prev_en_meu', models.FloatField(null=True)),
                ('notification_du_marche', models.DateField(null=True)),
                ('cao_attribution', models.DateField(null=True)),
                ('annee_d_individualisation', models.CharField(max_length=4, null=True)),
                ('annee_de_livraison', models.CharField(max_length=4, null=True)),
                ('nombre_de_lots', models.IntegerField(null=True)),
                ('mode_de_devolution', models.CharField(choices=[('Lots séparés', 'Separate'), ('Ent générale', 'General'), ('NC', 'Nc')], default='NC')),
                ('ppi', models.CharField()),
                ('etat_d_avancement', models.CharField(choices=[])),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='api.company')),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.establishment')),
                ('project_management', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='api.projectmanagement')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='api.representative')),
            ],
            options={
                'db_table': 'model_project',
            },
        ),
    ]
