# Generated by Django 4.2.18 on 2025-01-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='establishment',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['annee_de_livraison', 'cao_attribution', 'notification_du_marche']},
        ),
        migrations.AlterModelOptions(
            name='projectmanagement',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='representative',
            options={'ordering': ['label']},
        ),
    ]
