# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nearby_search.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nearby_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13nearby_search.proto\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"*\n\x0ePolygonRequest\x12\x18\n\x08vertices\x18\x01 \x03(\x0b\x32\x06.Point\"&\n\x0cZoneResponse\x12\x16\n\x06points\x18\x01 \x03(\x0b\x32\x06.Point2K\n\x13nearbySearchService\x12\x34\n\x12GetPointsInPolygon\x12\x0f.PolygonRequest\x1a\r.ZoneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nearby_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=23
  _globals['_POINT']._serialized_end=67
  _globals['_POLYGONREQUEST']._serialized_start=69
  _globals['_POLYGONREQUEST']._serialized_end=111
  _globals['_ZONERESPONSE']._serialized_start=113
  _globals['_ZONERESPONSE']._serialized_end=151
  _globals['_NEARBYSEARCHSERVICE']._serialized_start=153
  _globals['_NEARBYSEARCHSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
