# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nearby_search_pb2 as nearby__search__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nearby_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class nearbySearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPointsInPolygon = channel.unary_unary(
                '/nearbySearchService/GetPointsInPolygon',
                request_serializer=nearby__search__pb2.PolygonRequest.SerializeToString,
                response_deserializer=nearby__search__pb2.ZoneResponse.FromString,
                _registered_method=True)


class nearbySearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPointsInPolygon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_nearbySearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPointsInPolygon': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPointsInPolygon,
                    request_deserializer=nearby__search__pb2.PolygonRequest.FromString,
                    response_serializer=nearby__search__pb2.ZoneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nearbySearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nearbySearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class nearbySearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPointsInPolygon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nearbySearchService/GetPointsInPolygon',
            nearby__search__pb2.PolygonRequest.SerializeToString,
            nearby__search__pb2.ZoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
